<?php

return [
    'texts' => [
        'main_title' => 'Tecnologia que transforma comunidades',
        'slogan' => 'Tecnologia simples e poderosa para potencializar ações sociais e transformar comunidades.',
        'features_title' => 'Tudo que você precisa para gerir sua comunidade',
        'feature_1_title' => 'Gestão de Eventos Sem Caos',
        'feature_1_desc' => 'Organize mutirões, campanhas e atendimentos com agendamento inteligente.',
        'feature_2_title' => 'Benefícios com Transparência Total',
        'feature_2_desc' => 'Controle de estoque em tempo real, rastreabilidade e relatórios completos.',
        'feature_3_title' => 'Nenhuma Família Esquecida',
        'feature_3_desc' => 'Cadastro completo com histórico de atendimentos e necessidades específicas.',
        'steps_title' => 'Comece em poucos passos',
        'step_1_title' => 'Cadastre sua comunidade',
        'step_1_desc' => 'Cadastre sua comunidade em minutos.',
        'step_2_title' => 'Organize seus fluxos',
        'step_2_desc' => 'Organize seus fluxos e doações.',
        'step_3_title' => 'Engaje voluntários',
        'step_3_desc' => 'Engaje voluntários e famílias.',
        'step_4_title' => 'Acompanhe o impacto',
        'step_4_desc' => 'Acompanhe o impacto com dados reais.',
        'cta_button' => 'Começar',
        'login_button' => 'Entrar',
        'nav_home' => 'Inicio',
        'nav_benefits' => 'Benefícios',
        'nav_how_it_works' => 'Como Funciona',
        'footer_product' => 'Produto',
        'footer_product_1' => 'Funcionalidades',
        'footer_product_2' => 'Demonstração',
        'footer_product_3' => 'Preços',
        'footer_product_4' => 'Atualizações',
        'footer_company' => 'Empresa',
        'footer_company_1' => 'Sobre Nós',
        'footer_company_2' => 'Impacto Social',
        'footer_company_3' => 'Contato',
        'footer_company_4' => 'Blog',
        'footer_legal' => 'Legal',
        'footer_legal_1' => 'Termos de Uso',
        'footer_legal_2' => 'Política de Privacidade',
        'footer_legal_3' => 'Segurança de Dados',
        'footer_credit' => 'Desenvolvido com 💙 pela equipe',
        'footer_rights' => 'Todos os direitos reservados.',
    ],
];
